Repository pingcap/ng-monitoring, pull requests merged in 2022-04, with the labels that each got.

#122 pdvar: try best to notify and always return the latest value
  component/topsql/subscriber/default_subscriber_test.go
  component/topsql/subscriber/manager.go
  component/topsql/subscriber/manager_test.go
  config/pdvariable/pdvariable.go
  config/pdvariable/pdvariable_test.go
  tests/topsql_test.go
Labels: status/LGT1, status/can-merge

#123 config: try best to notify subscriber and always return the latest value
  component/conprof/http/api_test.go
  component/conprof/scrape/manager.go
  component/conprof/scrape/manager_test.go
  component/conprof/store/store_test.go
  component/domain/client.go
  component/domain/domain.go
  component/domain/domain_test.go
  component/topology/topology_test.go
  component/topsql/subscriber/default_subscriber.go
  component/topsql/subscriber/default_subscriber_test.go
  component/topsql/subscriber/manager.go
  component/topsql/subscriber/manager_test.go
  component/topsql/topsql.go
  config/config.go
  config/config_test.go
  config/pdvariable/pdvariable_test.go
  config/service_test.go
  main.go
  tests/topsql_test.go
Labels: status/LGT1, status/can-merge

#124 topo: try best to notify subscriber and always return the latest value
  component/conprof/http/api_test.go
  component/conprof/scrape/manager.go
  component/conprof/scrape/manager_test.go
  component/conprof/store/store_test.go
  component/topology/discovery.go
  component/topology/topology.go
  component/topology/topology_test.go
  component/topsql/subscriber/default_subscriber_test.go
  component/topsql/subscriber/manager.go
  component/topsql/subscriber/manager_test.go
  config/config_test.go
  tests/topsql_test.go
Labels: status/LGT1, status/can-merge

#125 refine: extract subscriber
  component/subscriber/main_test.go
  component/subscriber/manager.go
  component/subscriber/mock_sub_controller_test.go
  component/subscriber/sub_controller.go
  component/subscriber/subscriber.go
  component/subscriber/subscriber_test.go
  component/topsql/mock/mem_store.go
  component/topsql/subscriber/default_subscriber.go
  component/topsql/subscriber/default_subscriber_test.go
  component/topsql/subscriber/manager.go
  component/topsql/subscriber/scraper.go
  component/topsql/subscriber/scraper_test.go
  component/topsql/subscriber/subscriber.go
  component/topsql/subscriber/subscriber_test.go
  component/topsql/topsql.go
  go.mod
  go.sum
Labels: status/LGT1, status/can-merge

#126 enable conprof by default
  config/config.go
Labels: status/LGT1, do-not-merge/needs-linked-issue

#128 Revert "support profiling tiflash (#47)" (#118)
  component/conprof/http/api.go
  component/conprof/scrape/manager.go
  component/conprof/scrape/manager_test.go
Labels: status/LGT1, status/can-merge, cherry-pick-approved

#129 conprof: fix genjidb(badger) gc doesn't work problem(#115)(#119)
  component/conprof/store/store_test.go
  database/document/document.go
  database/document/document_test.go
  database/document/gc.go
  database/timeseries/syscall_not_linux_unix.go
  go.mod
  go.sum
  utils/testutil/util.go
Labels: status/LGT1, status/can-merge, cherry-pick-approved

#130 test: add github action for ci
  .github/workflows/ci.yml
Labels: status/LGT1, status/can-merge

#131 fix test after contprof is enabled by default
  config/config_test.go
Labels: status/LGT1, status/can-merge
