Repository pingcap/ng-monitoring, pull requests merged in 2023-11, with the labels that each got.

#198 conprof: reuse convertDotToSVG to generate tikv heap profile svg
  component/conprof/jeprof/jeprof.go
Labels: size/S, lgtm, approved

#199 conprof: support heap profiling for tikv
  component/conprof/http/api.go
  component/conprof/http/api_test.go
  component/conprof/jeprof/jeprof.go
  component/conprof/jeprof/jeprof.in
  component/conprof/meta/meta.go
  component/conprof/scrape/manager.go
  component/conprof/scrape/manager_test.go
  component/conprof/scrape/scrape.go
  utils/testutil/util.go
Labels: lgtm, approved, size/XXL

#201 *: add fips build support
  Makefile
  component/conprof/http/api_test.go
  utils/printer/fips.go
Labels: lgtm, approved, size/M

#210 OWNERS: add TiDB cloud o11y team to owners
  OWNERS
Labels: lgtm, approved, size/XS

#207 *: update dependencies for security reason
  component/conprof/scrape/manager_test.go
  component/domain/domain_test.go
  component/subscriber/main_test.go
  component/topsql/subscriber/main_test.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#208 *: update dependencies for security reason
  component/conprof/scrape/manager_test.go
  component/domain/domain_test.go
  component/topsql/subscriber/main_test.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#213 tsdb: update vm to v1.76.1; expose more params
  config/config.go
  config/config.toml.example
  config/config_test.go
  database/timeseries/vm.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, size/XXL
