Repository pingcap/ng-monitoring, pull requests merged in 2023-12, with the labels that each got.

#216 *: add fips build support (#201)
  Makefile
  component/conprof/http/api_test.go
  utils/printer/fips.go
Labels: lgtm, approved, size/M

#205 conprof: use debug=1 for goroutine profile to avoid STW
  component/conprof/scrape/manager.go
Labels: lgtm, approved, size/XS

#226 *: update golangci-lint version to fix ci
  Makefile
  config/config.go
  config/config_test.go
Labels: size/S, lgtm, approved
